import type { NextPage } from 'next';
import Head from 'next/head';

import Main from 'screens/Main';

import { FlexBox } from '@components/Box';
import { Header } from '@components/Header';

const Home: NextPage = () => {
  return (
    <FlexBox direction="column" align="center">
      <Head>
        <title>Gerenciamento de Alunos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <Main />
      </main>

      <footer />
    </FlexBox>
  );
};

export default Home;
