import type { NextPage } from 'next';
import Head from 'next/head';

import { Header } from '@components/Header';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Gerenciamento de Alunos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
      </main>

      <footer />
    </>
  );
};

export default Home;
